# Generated by Django 2.2.5 on 2019-10-22 03:54

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20191022_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(max_length=10000, storage=common.models.OverwriteStorage(), upload_to=''),
        ),
    ]
