# Generated by Django 2.2.5 on 2019-10-17 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('version', models.CharField(choices=[('CentOS 6', 'CentOS 6'), ('CentOS 7', 'CentOS 7')], max_length=200, verbose_name='版本')),
                ('config', models.CharField(choices=[('4C 8G 40G', '4C 8G 40G'), ('8C 16G 80G', '8C 16G 80G'), ('8C 32G 100G', '8C 32G 100G')], max_length=200, verbose_name='配置')),
                ('position', models.CharField(choices=[('阿里云', '阿里云'), ('电信机房', '电信机房'), ('坪山机房', '坪山机房')], max_length=200, verbose_name='位置')),
                ('type', models.CharField(choices=[('nginx', 'nginx'), ('java', 'java'), ('mysql', 'mysql'), ('redis', 'redis')], default='java', max_length=200, verbose_name='类别')),
                ('env', models.CharField(choices=[('test', '测试环境'), ('pro', '生产环境')], default='test', max_length=200, verbose_name='环境')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
            },
        ),
        migrations.CreateModel(
            name='HostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('script_dir', models.CharField(default='/data/scripts/deploy_jar.sh', max_length=200, verbose_name='路径')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
            },
        ),
        migrations.CreateModel(
            name='JarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('url', models.CharField(max_length=200, verbose_name='访问地址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
        migrations.CreateModel(
            name='Jarapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('jarname', models.CharField(max_length=200, verbose_name='包名')),
                ('port', models.IntegerField(default=8080, verbose_name='端口号')),
                ('jar_dir', models.CharField(default='/usr/local/jars', max_length=200, verbose_name='部署路径')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('c_script', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='c_script', to='deployjar.Script', verbose_name='控制脚本')),
                ('d_script', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='d_script', to='deployjar.Script', verbose_name='发布脚本')),
                ('host', models.ManyToManyField(to='deployjar.Host', verbose_name='主机')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='deployjar.HostUser', verbose_name='管理用户')),
            ],
            options={
                'verbose_name': '模块(旧)',
                'verbose_name_plural': '模块(旧)',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('port', models.IntegerField(verbose_name='端口号')),
                ('package', models.CharField(max_length=200, verbose_name='包名')),
                ('dir', models.CharField(default='/usr/local/', max_length=200, verbose_name='部署路径')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '实例',
                'verbose_name_plural': '实例',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='hostuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.HostUser', verbose_name='系统管理员'),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('url', models.CharField(max_length=200, verbose_name='URL 地址')),
                ('ip', models.CharField(max_length=200, verbose_name='外网 IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('disc', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('nginx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='Nginx 服务器')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
                'ordering': ['name'],
            },
        ),
    ]
