# Generated by Django 2.2.5 on 2019-09-25 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('version', models.CharField(choices=[('CentOS 6', 'CentOS 6'), ('CentOS 7', 'CentOS 7')], max_length=200, verbose_name='版本')),
                ('config', models.CharField(choices=[('4C 8G 40G', '4C 8G 40G'), ('8C 16G 80G', '8C 16G 80G'), ('8C 32G 100G', '8C 32G 100G')], max_length=200, verbose_name='配置')),
                ('position', models.CharField(choices=[('阿里云', '阿里云'), ('电信机房', '电信机房')], max_length=200, verbose_name='位置')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
            },
        ),
        migrations.CreateModel(
            name='HostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('script_dir', models.CharField(default='/data/scripts/deploy_jar.sh', max_length=200, verbose_name='路径')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
            },
        ),
        migrations.CreateModel(
            name='Jarapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('port', models.IntegerField(default=8080, verbose_name='端口号')),
                ('jar_dir', models.CharField(default='/usr/local/jar8080', max_length=200, verbose_name='部署路径')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('host', models.ManyToManyField(to='deployjar.Host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='hostuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.HostUser', verbose_name='系统管理员'),
        ),
    ]
