# Generated by Django 2.2.5 on 2019-10-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0002_auto_20191017_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarmodel',
            name='pro_instance',
        ),
        migrations.RemoveField(
            model_name='jarmodel',
            name='test_instance',
        ),
    ]
