# Generated by Django 2.2.5 on 2019-09-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0002_auto_20190926_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarapp',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='deployjar.HostUser', verbose_name='管理用户'),
        ),
        migrations.AlterField(
            model_name='jarapp',
            name='c_script',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='c_script', to='deployjar.Script', verbose_name='控制脚本'),
        ),
    ]
