# Generated by Django 2.2.5 on 2019-10-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0003_auto_20191017_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='name',
        ),
    ]
