# Generated by Django 2.2.5 on 2019-10-15 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0003_auto_20190926_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('port', models.IntegerField(verbose_name='端口号')),
                ('package', models.CharField(max_length=200, verbose_name='包名')),
                ('dir', models.CharField(default='/usr/local/', max_length=200, verbose_name='部署路径')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '实例',
                'verbose_name_plural': '实例',
            },
        ),
        migrations.CreateModel(
            name='JarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('url', models.CharField(max_length=200, verbose_name='访问地址')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('instance', models.ManyToManyField(to='deployjar.Instance')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
    ]
