# Generated by Django 2.2.5 on 2019-10-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0004_remove_instance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deployjar.JarModel', verbose_name='模块名'),
            preserve_default=False,
        ),
    ]
