# Generated by Django 2.2.5 on 2019-10-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('deployjar', '0004_instance_jarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarmodel',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='项目'),
        ),
    ]
