# Generated by Django 2.2.5 on 2019-10-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0005_jarmodel_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jarmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='项目'),
        ),
    ]
