# Generated by Django 2.2.5 on 2019-10-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0005_instance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='jarmodel',
            name='manager',
            field=models.CharField(default='研发部', max_length=200, verbose_name='负责人'),
            preserve_default=False,
        ),
    ]
