# Generated by Django 2.2.5 on 2019-10-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0006_auto_20191015_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='env',
            field=models.CharField(choices=[('test', '测试环境'), ('pro', '生产环境')], default='test', max_length=200, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='jarmodel',
            name='instance',
            field=models.ManyToManyField(to='deployjar.Instance', verbose_name='实例'),
        ),
    ]
