# Generated by Django 2.2.5 on 2019-10-18 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0007_auto_20191018_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysqldb',
            options={'verbose_name': 'MySQL 数据库', 'verbose_name_plural': 'MySQL 数据库'},
        ),
    ]
