# Generated by Django 2.2.5 on 2019-10-18 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0008_auto_20191018_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqldb',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='mysqldb',
            name='dir',
            field=models.CharField(default='/usr/local/mysql/data', max_length=200, verbose_name='路径'),
        ),
        migrations.AddField(
            model_name='mysqldb',
            name='instance',
            field=models.ManyToManyField(to='deployjar.MySQLInstance', verbose_name='MySQL 实例'),
        ),
        migrations.AddField(
            model_name='mysqldb',
            name='manager',
            field=models.CharField(default=1, max_length=200, verbose_name='管理员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mysqldb',
            name='password',
            field=models.CharField(default='111111', max_length=200, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='mysqldb',
            name='user',
            field=models.CharField(default='dbuser', max_length=200, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='mysqlinstance',
            name='type',
            field=models.CharField(choices=[('primary', '主节点'), ('subordinate', '从节点')], max_length=200, verbose_name='类型'),
        ),
    ]
