# Generated by Django 2.2.5 on 2019-10-18 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('deployjar', '0009_auto_20191018_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqldb',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='项目'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mysqldb',
            name='dir',
            field=models.CharField(default='/usr/local/mysql/data', max_length=200, verbose_name='数据库路径'),
        ),
    ]
