# Generated by Django 2.2.5 on 2019-10-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0011_auto_20191016_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jarmodel',
            name='test_instance',
            field=models.ManyToManyField(related_name='test', to='deployjar.Instance', verbose_name='测试实例'),
        ),
    ]
