# Generated by Django 2.2.5 on 2019-10-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0011_auto_20191023_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hostuser',
            field=models.CharField(default='root', max_length=200, verbose_name='系统管理员'),
        ),
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default='bsbnet', max_length=200, verbose_name='密码'),
        ),
    ]
