# Generated by Django 2.2.5 on 2019-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0012_auto_20191016_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='type',
            field=models.CharField(choices=[('nginx', 'nginx'), ('java', 'java'), ('mysql', 'mysql'), ('redis', 'redis')], default='java', max_length=200, verbose_name='类别'),
        ),
    ]
