# Generated by Django 2.2.5 on 2019-10-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0014_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name'], 'verbose_name': '域名', 'verbose_name_plural': '域名'},
        ),
        migrations.AlterModelOptions(
            name='jarapp',
            options={'verbose_name': '模块(旧)', 'verbose_name_plural': '模块(旧)'},
        ),
        migrations.AddField(
            model_name='domain',
            name='disc',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='ip',
            field=models.CharField(max_length=200, verbose_name='外网 IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='position',
            field=models.CharField(choices=[('阿里云', '阿里云'), ('电信机房', '电信机房'), ('坪山机房', '坪山机房')], max_length=200, verbose_name='位置'),
        ),
    ]
