# Generated by Django 2.2.5 on 2019-10-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0014_script_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='script_dir',
            field=models.CharField(default='/data/scripts/', max_length=200, verbose_name='路径'),
        ),
    ]
