# Generated by Django 2.2.5 on 2019-10-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0015_auto_20191031_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jarapp',
        ),
    ]
