# Generated by Django 2.2.5 on 2019-11-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0016_delete_jarapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=200, verbose_name='英文名')),
                ('cn_name', models.CharField(max_length=200, verbose_name='中文名')),
            ],
            options={
                'verbose_name': '环境类型',
                'verbose_name_plural': '环境类型',
            },
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='主机类别')),
            ],
            options={
                'verbose_name': '主机类别',
                'verbose_name_plural': '主机类别',
            },
        ),
    ]
