# Generated by Django 2.2.5 on 2019-11-04 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191022_1231'),
        ('deployjar', '0017_hostenv_hosttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='项目')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.HostType', verbose_name='类别')),
            ],
            options={
                'verbose_name': '配置文件',
                'verbose_name_plural': '配置文件',
            },
        ),
    ]
