# Generated by Django 2.2.5 on 2019-11-05 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191022_1231'),
        ('deployjar', '0018_configfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configfile',
            options={'ordering': ['file_name'], 'verbose_name': '配置文件', 'verbose_name_plural': '配置文件'},
        ),
        migrations.AlterUniqueTogether(
            name='configfile',
            unique_together={('project', 'file_name')},
        ),
    ]
