# Generated by Django 2.2.5 on 2019-11-06 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0019_auto_20191105_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=200, unique=True, verbose_name='英文名')),
                ('cn_name', models.CharField(max_length=200, unique=True, verbose_name='中文名')),
            ],
            options={
                'verbose_name': '任务类别',
                'verbose_name_plural': '任务类别',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployjar.TaskType', verbose_name='类别'),
        ),
    ]
