# Generated by Django 2.2.5 on 2019-11-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0021_auto_20191106_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosttype',
            options={'ordering': ['name'], 'verbose_name': '主机类别', 'verbose_name_plural': '主机类别'},
        ),
        migrations.AlterField(
            model_name='task',
            name='script',
            field=models.CharField(max_length=200, verbose_name='脚本文件名'),
        ),
    ]
