# Generated by Django 2.2.5 on 2019-11-12 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0022_auto_20191112_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.HostType', verbose_name='类别'),
        ),
    ]
