# Generated by Django 2.2.5 on 2019-11-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0023_auto_20191112_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='host',
            field=models.ForeignKey(limit_choices_to={'type__name': 'mysql'}, on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
    ]
