# Generated by Django 2.2.5 on 2019-11-18 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191022_1231'),
        ('deployjar', '0024_auto_20191112_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxHostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, verbose_name='域名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
            },
        ),
        migrations.CreateModel(
            name='NginxInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=80, verbose_name='端口号')),
                ('version', models.CharField(default='1.9', max_length=200, verbose_name='版本号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('config_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.ConfigFile', verbose_name='主配置文件')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机')),
            ],
            options={
                'verbose_name': 'NGINX 实例',
                'verbose_name_plural': 'NGINX 实例',
            },
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['name'], 'verbose_name': '项目访问地址', 'verbose_name_plural': '项目访问地址'},
        ),
        migrations.AlterField(
            model_name='instance',
            name='host',
            field=models.ForeignKey(limit_choices_to={'type__name': 'java'}, on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='mysqlinstance',
            name='host',
            field=models.ForeignKey(limit_choices_to={'type__name': 'mysql'}, on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='IP 地址'),
        ),
        migrations.CreateModel(
            name='NginxVhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=80, verbose_name='端口号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('config_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.ConfigFile', verbose_name='配置文件')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.NginxHostName', verbose_name='Nginx 虚拟主机名')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.NginxInstance', verbose_name='Nginx 实例')),
            ],
            options={
                'verbose_name': 'Nginx 虚拟主机名',
                'verbose_name_plural': 'Nginx 虚拟主机名',
            },
        ),
    ]
