# Generated by Django 2.2.5 on 2019-11-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0025_auto_20191118_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxinstance',
            name='host',
            field=models.ForeignKey(limit_choices_to={'type__name': 'nginx'}, on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
    ]
