# Generated by Django 2.2.5 on 2019-11-19 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0028_mongodbcluster_mongodbdatabase_mongodbinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mongodbinstance',
            name='host',
            field=models.ForeignKey(limit_choices_to={'type__name': 'mongodb'}, on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
    ]
