# Generated by Django 2.2.5 on 2019-11-20 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191022_1231'),
        ('deployjar', '0029_auto_20191119_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedisCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='集群名')),
                ('type', models.CharField(choices=[('单实例', '单实例'), ('主从', '主从'), ('哨兵模式', '哨兵模式')], max_length=200, verbose_name='类别')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='项目使用')),
            ],
            options={
                'verbose_name': 'Redis 集群',
                'verbose_name_plural': 'Redis 集群',
            },
        ),
        migrations.AlterField(
            model_name='mongodbdatabase',
            name='password',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mongodbdatabase',
            name='user',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=200, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mongodbinstance',
            name='role',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary '), ('arbiter', 'arbiter'), ('route', 'route')], max_length=200, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='RedisInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=6379, verbose_name='端口号')),
                ('role', models.CharField(choices=[('main', 'main'), ('subordinate', 'subordinate')], max_length=200, verbose_name='角色')),
                ('version', models.CharField(default='4.0', max_length=200, verbose_name='版本')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.RedisCluster', verbose_name='集群名')),
                ('host', models.ForeignKey(limit_choices_to={'type__name': 'redis'}, on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机')),
            ],
            options={
                'verbose_name': 'Redis 实例',
                'verbose_name_plural': 'Redis 实例',
            },
        ),
    ]
