# Generated by Django 2.2.5 on 2019-11-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191022_1231'),
        ('deployjar', '0030_auto_20191120_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rediscluster',
            name='project',
        ),
        migrations.AddField(
            model_name='rediscluster',
            name='project',
            field=models.ManyToManyField(to='common.Project', verbose_name='项目使用'),
        ),
    ]
