# Generated by Django 2.2.5 on 2019-11-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployjar', '0032_kafkacluster_kafkainstance_zookeepercluster_zookeeperinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jarmodel',
            options={'verbose_name': 'JAVA 模块', 'verbose_name_plural': 'JAVA 模块'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-type__en_name'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterModelOptions(
            name='zookeepercluster',
            options={'verbose_name': 'Zookeeper 集群', 'verbose_name_plural': 'Zookeeper 集群'},
        ),
        migrations.AlterModelOptions(
            name='zookeeperinstance',
            options={'verbose_name': 'Zookeeper 实例', 'verbose_name_plural': 'Zookeeper 实例'},
        ),
        migrations.AddField(
            model_name='mongodbinstance',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='mongodbinstance',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='redisinstance',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='kafkainstance',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.KafkaCluster', verbose_name='集群名'),
        ),
        migrations.AlterField(
            model_name='kafkainstance',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='kafkainstance',
            name='port',
            field=models.IntegerField(default=9092, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='mongodbinstance',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='mysqlinstance',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='IP 地址'),
        ),
        migrations.AlterField(
            model_name='nginxhostname',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='nginxinstance',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='redisinstance',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='zookeeperinstance',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.ZookeeperCluster', verbose_name='集群名'),
        ),
        migrations.AlterField(
            model_name='zookeeperinstance',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployjar.Host', verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='zookeeperinstance',
            name='port',
            field=models.IntegerField(default=2181, verbose_name='端口号'),
        ),
    ]
